---
title: "Writing Functions"
author: "Tanu"
date: "10/24/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(p8105.datasets)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

# Z score
```{r}
x = rnorm(30, mean = 4, sd = 2.3)
y=rnorm(n=30, mean=24, sd=2.3)

(x - mean(x)) / sd(x)
```

Now a function

```{r}
z_scores = function(x) {
  if(!is.numeric(x)) {
    stop("x should be numeric")
    } else if (length(x<3)){
    stop("x should be longer than 3")
}
  z = (x - mean(x)) / sd(x)
  z
}

```

Try out the function

```{r, error=TRUE}
z_scores(x=y)

z_scores(x=iris)
```
# Multiple Outputs

```{r}
mean_and_sd = function(input_x) {
  if(!is.numeric(input_x)) {
    stop("x should be numeric")
    } else if (length(input_x<3)){
    stop("x should be longer than 3")
    }

list(
mean_input= mean(input_x),
sd_input= sd(input_x),
z_score=input_x-mean(input_x) /sd(input_x)
)
}
```

Test this function

```{r, error=TRUE}
mean_and_sd((input_x=y))
```

Multiple inputs
```{r}
sim_data= tibble(
  x=rnorm(30, mean=1, sd=1),
  y=2+3*x +rnorm(30,0,1)
)

sim_data %>% 
  ggplot(aes(x=y, y=y)) +
  geom_point()

ls_fit=lm(y~x, data=sim_data)

beta0_hat=coef(ls_fit)[1]
beta0_hat=coef(ls_fit)[2]

```

```{r}
sim_regression = function(n) {
  
  sim_data = tibble(
  x= rnorm(30, mean=1, sd=1),
  y= 2+ 3*x + rnorm(30, 0, 1)
)
  
ls_fit = lm(y ~ x, data = sim_data)
  
tibble(
  beta0_hat = coef(ls_fit)[1],
  beta1_hat = coef(ls_fit)[2]
)
}

sim_regression(n = 30)
```


```{r}
sim_regression = function(n, beta0 = 2, beta1 = 3) {
  
  sim_data = tibble(
  x= rnorm(n, mean=1, sd=1),
  y= beta0 + beta1 * x + rnorm(n, 0, 1)
)
  
ls_fit = lm(y ~ x, data = sim_data)
  
tibble(
  beta0_hat = coef(ls_fit)[1],
  beta1_hat = coef(ls_fit)[2]
)
}

sim_regression(n = 14, beta0 = 24, beta1 = 3)
```

#Scrape lots of Napolean

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-title") %>%
  html_text()

review_stars = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = dynamite_html %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

```{r}
read_page_reviews <- function(url) {
  
  h = read_html(url)
  
  review_titles = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  review_stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  review_text = h %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()
  
  tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
}
```

```{r}

url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_urls = str_c(url_base, 1:5)

dynamite_reviews = bind_rows(
  read_page_reviews(vec_urls[1]),
  read_page_reviews(vec_urls[2]),
  read_page_reviews(vec_urls[3]),
  read_page_reviews(vec_urls[4]),
  read_page_reviews(vec_urls[5])
)
```

